- name: Coping {{COMPONENT}} Repo File
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongodb.repo
    
- name: Installing {{COMPONENT}} Server
  ansible.builtin.yum:
    name: mongodb-org
    state: present

# - name: Starting {{COMPONENT}} Service
#   ansible.builtin.systemd:
#     name: "{{COMPONENT}}"
#     state: started
#     enabled: yes
#     daemon_reload:  yes

- name: Updating {{COMPONENT}} Config
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Starting {{COMPONENT}} Service
  ansible.builtin.service:
    name: mongod
    state: started
    enabled: yes

- name: Downloading & Unzip the {{COMPONENT}} schema files
  ansible.builtin.include_role:
    name: common
    tasks_from: download-and-extract

- name: Loading Catalogue Schema
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/{{item}}.js"
    idempotent: yes
  loop:
    - catalogue
    - users
