- name: Demo on Outputs
  hosts: all
  tasks:
    - name: execute of uptime 
      ansible.builtin.shell: uptime
      register: OUT

    - name: printing output of uptime
      ansible.builtin.debug:
        msg: "{{OUT}}""