- name: Installing Nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: Downloading & Unzip the {{COMPONENT}} schema files
  ansible.builtin.include_role:
    name: common
    tasks_from: download-and-extract

- name: Cleanup the old html content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Coping {{COMPONENT}} content to nginx path
  ansible.builtin.copy:
    src: /tmp/frontend-main/static/
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Copying proxy config
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf
  notify: Restarting Nginx Service

- name: Starting Nginx Service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: Configuring the HostName
  ansible.builtin.include_role:
    name: common
    tasks_from: set-hostname