- name: Installing Nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: Downloading & Unzip the frontend dependency files
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/frontend/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: Cleanup the old html content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Coping frontend content to nginx path
  ansible.builtin.copy:
    src: /tmp/frontend-main/static/
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Copying proxy config
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf
    remote_src: yes

- name: Starting Nginx Service
  ansible.builtin.service:
    name: nginx
    state: restart
    enable: yes