- name: Installing Maven
  ansible.builtin.yum:
    name: golang
    state: present

- name: Creating {{APPUSER}} for {{COMPONENT}}
  ansible.builtin.include_role:
    name: common
    tasks_from: create-user

- name: Downloading & Unzip the {{COMPONENT}} schema files
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/dispatch/archive/refs/heads/main.zip
    dest: /tmp
    remote_src: yes 

- name: Cleanup the old content
  ansible.builtin.file:
    path: /home/{{APPUSER}}/{{COMPONENT}}/
    state: absent
  ignore_errors: true

- name: Coping {{COMPONENT}} of {{APPUSER}}
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/{{APPUSER}}/{{COMPONENT}}/
    remote_src: yes
  become_user: "{{APPUSER}}"
  ignore_errors: true

- name: Generating Packages
  ansible.builtin.shell: go mod init dispatch && go get && go build
  become_user: "{{APPUSER}}"
  args:
    chdir: /home/{{APPUSER}}/{{COMPONENT}}/

- name: Configuring {{COMPONENT}} Service
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd-start-svc