- name: Installing Maven
  ansible.builtin.package:
    name: maven
    state: present

- name: Creating application user
  ansible.builtin.include_role:
    name: common
    tasks_from: create-user

- name: Downloading & Unzip the {{COMPONENT}} files
  ansible.builtin.include_role:
    name: common
    tasks_from: download-and-extract