- name: Configure the Yum Repo
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_16.x | bash

- name: Installing NodeJS
  ansible.builtin.package:
    name: "{{item}}"
    state: present
  loop:
    - nodejs
    - gcc-c++

- name: Creating {{APPUSER}} for {{COMPONENT}}
  ansible.builtin.include_role:
    name: common
    tasks_from: create-user

- name: Cleanup the old content
  ansible.builtin.file:
    path: /home/{{APPUSER}}/{{COMPONENT}}/
    state: absent

- name: Downloading & Unzip the {{COMPONENT}} files
  ansible.builtin.include_role:
    name: common
    tasks_from: download-and-extract

- name: Install NodeJS packages based on package.json file 
  community.general.npm:
    path: /home/{{APPUSER}}/{{COMPONENT}}/

- name: Configuring {{COMPONENT}} Service
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd-start-svc

- name: Configuring the HostName
  ansible.builtin.include_role:
    name: common
    tasks_from: set-hostname

# - name: Creating/Adding roboshop User
#   ansible.builtin.user:
#     name: "{{APPUSER}}"
#     comment: Roboshop application user
