- name: Configure the Yum Repo
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_16.x | bash

- name: Installing NodeJS
  ansible.builtin.package:
    name: "{{item}}"
    state: present
  loop:
    - nodejs
    - gcc-c++

- name: Creating/Adding roboshop User
  ansible.builtin.user:
    name: "{{APPUSER}}"
    comment: Roboshop application user

- name: Cleanup the old html content
  ansible.builtin.file:
    path: /home/{{APPUSER}}/{{COMPONENT}}/
    state: absent

- name: Downloading & Unzip the {{COMPONENT}} schema files
  ansible.builtin.include_role:
    name: common
    tasks_from: download-and-extract

- name: Coping {{COMPONENT}} of {{APPUSER}}
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/{{APPUSER}}/{{COMPONENT}}/
    remote_src: yes
  become_user: "{{APPUSER}}"

- name: Install NodeJS packages based on package.json file 
  community.general.npm:
    path: /home/{{APPUSER}}/{{COMPONENT}}/

- name: Copying proxy config
  ansible.builtin.copy:
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service

- name: Starting {{COMPONENT}} Service
  ansible.builtin.systemd:
    name: "{{COMPONENT}}"
    state: restarted
    enabled: yes
    daemon_reload:  yes